#!/bin/sh
set -e
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd $DIR

if [ ! -d libs ];
then
    mkdir libs
fi

if [ ! -d libs/google-play-services_lib ];
then
    if [ ! -f ~/.soomla/cache/android-profile/google-play-services_lib-5.0.89.zip ];
    then
        curl -L -o ~/.soomla/cache/android-profile/google-play-services_lib-5.0.89.zip.tmp http://library.soom.la/fetch/android-profile-google-play-services/5.0.89?cf=dl_deps
        mv ~/.soomla/cache/android-profile/google-play-services_lib-5.0.89.zip.tmp ~/.soomla/cache/android-profile/google-play-services_lib-5.0.89.zip
    fi
    unzip ~/.soomla/cache/android-profile/google-play-services_lib-5.0.89.zip -d libs/
fi