#!/bin/sh
set -e
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd $DIR

if [ ! -d libs ];
then
    mkdir libs
fi

if [ ! -h libs/AndroidProfile.jar ];
then
	ln -s ../../../build/AndroidProfile.jar libs/AndroidProfile.jar
fi

if [ ! -h libs/SoomlaAndroidCore.jar ];
then
	ln -s ../../../SoomlaAndroidProfile/libs/SoomlaAndroidCore.jar libs/SoomlaAndroidCore.jar
fi

if [ ! -h libs/square-otto-1.3.2.jar ];
then
	ln -s ../../../SoomlaAndroidProfile/libs/square-otto-1.3.2.jar libs/square-otto-1.3.2.jar
fi

if [ ! -d libs/google-play-services_lib ];
then
    if [ ! -f ~/.soomla/cache/android-profile/google-play-services_lib-5.0.89.zip ];
    then
        curl -L -o ~/.soomla/cache/android-profile/google-play-services_lib-5.0.89.zip.tmp http://library.soom.la/fetch/android-profile-google-play-services/5.0.89?cf=dl_deps
        mv ~/.soomla/cache/android-profile/google-play-services_lib-5.0.89.zip.tmp ~/.soomla/cache/android-profile/google-play-services_lib-5.0.89.zip
    fi
    unzip ~/.soomla/cache/android-profile/google-play-services_lib-5.0.89.zip -d libs/
fi