#!/bin/sh
set -e
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd $DIR

ANDROID_PROFILE_CACHE=~/.soomla/cache/android-profile
mkdir -p $ANDROID_PROFILE_CACHE

mkdir -p libs

if [ ! -h libs/AndroidProfile.jar ];
then
	ln -s ../../../build/AndroidProfile.jar libs/AndroidProfile.jar
fi

if [ ! -h libs/SoomlaAndroidCore.jar ];
then
	ln -s ../../../SoomlaAndroidProfile/libs/SoomlaAndroidCore.jar libs/SoomlaAndroidCore.jar
fi

if [ ! -h libs/square-otto-1.3.2.jar ];
then
	ln -s ../../../SoomlaAndroidProfile/libs/square-otto-1.3.2.jar libs/square-otto-1.3.2.jar
fi

GPS_ARCH_NAME=google-play-services_lib-5.0.89.zip
if [ ! -d libs/google-play-services_lib ];
then
    if [ ! -f $ANDROID_PROFILE_CACHE/$GPS_ARCH_NAME ];
    then
        echo "Downloading Google Play Services lib..."
        curl -L -o $ANDROID_PROFILE_CACHE/$GPS_ARCH_NAME.tmp http://library.soom.la/fetch/android-profile-google-play-services/5.0.89?cf=dl_deps
        mv $ANDROID_PROFILE_CACHE/$GPS_ARCH_NAME.tmp $ANDROID_PROFILE_CACHE/$GPS_ARCH_NAME
    fi
    unzip $ANDROID_PROFILE_CACHE/$GPS_ARCH_NAME -d libs/
fi