#!/bin/sh
set -e
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd $DIR

./download_deps.sh

ant -buildfile android-profile-twitter.xml -Dsoomla.filename="AndroidProfileTwitter" all

cd - > /dev/null
