#!/bin/sh
set -e
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd $DIR

ANDROID_PROFILE_CACHE=~/.soomla/cache/android-profile
mkdir -p $ANDROID_PROFILE_CACHE

mkdir -p libs

if [ ! -h libs/AndroidProfile.jar ];
then
	ln -s ../../../build/AndroidProfile.jar libs/AndroidProfile.jar
fi

if [ ! -h libs/SoomlaAndroidCore.jar ];
then
	ln -s ../../../SoomlaAndroidProfile/libs/SoomlaAndroidCore.jar libs/SoomlaAndroidCore.jar
fi

TWITTER4J_ASYNC_NAME=twitter4j-async-4.0.2.jar
if [ ! -f libs/$TWITTER4J_ASYNC_NAME ];
then
    if [ ! -f $ANDROID_PROFILE_CACHE/$TWITTER4J_ASYNC_NAME ];
    then
        echo "Downloading Twitter4J Async..."
        curl -Lo $ANDROID_PROFILE_CACHE/$TWITTER4J_ASYNC_NAME.tmp http://twitter4j.org/maven2/org/twitter4j/twitter4j-async/4.0.2/twitter4j-async-4.0.2.jar
        mv  $ANDROID_PROFILE_CACHE/$TWITTER4J_ASYNC_NAME.tmp $ANDROID_PROFILE_CACHE/$TWITTER4J_ASYNC_NAME
    fi
    cp $ANDROID_PROFILE_CACHE/$TWITTER4J_ASYNC_NAME libs/$TWITTER4J_ASYNC_NAME
fi

TWITTER4J_CORE_NAME=twitter4j-core-4.0.2.jar
if [ ! -f libs/$TWITTER4J_CORE_NAME ];
then
    if [ ! -f $ANDROID_PROFILE_CACHE/$TWITTER4J_CORE_NAME ];
    then
        echo "Downloading Twitter4J Core..."
        curl -Lo $ANDROID_PROFILE_CACHE/$TWITTER4J_CORE_NAME.tmp http://twitter4j.org/maven2/org/twitter4j/twitter4j-core/4.0.2/twitter4j-core-4.0.2.jar
        mv  $ANDROID_PROFILE_CACHE/$TWITTER4J_CORE_NAME.tmp $ANDROID_PROFILE_CACHE/$TWITTER4J_CORE_NAME
    fi
    cp $ANDROID_PROFILE_CACHE/$TWITTER4J_CORE_NAME libs/$TWITTER4J_CORE_NAME
fi
