#!/bin/sh
set -e
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd $DIR

mkdir -p libs

if [ ! -f libs/twitter4j-async-4.0.2.jar ];
then
    if [ ! -f ~/.soomla/cache/android-profile/twitter4j-async-4.0.2.jar ];
    then
        curl -o ~/.soomla/cache/android-profile/twitter4j-async-4.0.2.jar.tmp http://twitter4j.org/maven2/org/twitter4j/twitter4j-async/4.0.2/twitter4j-async-4.0.2.jar
        mv  ~/.soomla/cache/android-profile/twitter4j-async-4.0.2.jar.tmp ~/.soomla/cache/android-profile/twitter4j-async-4.0.2.jar
    fi
    cp ~/.soomla/cache/android-profile/twitter4j-async-4.0.2.jar libs/twitter4j-async-4.0.2.jar
fi

if [ ! -f libs/twitter4j-core-4.0.2.jar ];
then
    if [ ! -f ~/.soomla/cache/android-profile/twitter4j-core-4.0.2.jar ];
    then
        curl -o ~/.soomla/cache/android-profile/twitter4j-core-4.0.2.jar.tmp http://twitter4j.org/maven2/org/twitter4j/twitter4j-async/4.0.2/twitter4j-core-4.0.2.jar
        mv  ~/.soomla/cache/android-profile/twitter4j-core-4.0.2.jar.tmp ~/.soomla/cache/android-profile/twitter4j-core-4.0.2.jar
    fi
    cp ~/.soomla/cache/android-profile/twitter4j-core-4.0.2.jar libs/twitter4j-core-4.0.2.jar
fi