#!/bin/sh
set -e
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd $DIR

mkdir -p libs

if [ ! -h libs/SoomlaAndroidCore.jar ];
then
    ln -s ../../submodules/soomla-android-core/build/SoomlaAndroidCore.jar libs/SoomlaAndroidCore.jar
fi
if [ ! -h libs/square-otto-1.3.2.jar ];
then
    ln -s ../../submodules/soomla-android-core/build/square-otto-1.3.2.jar libs/square-otto-1.3.2.jar
fi
