#!/bin/sh
set -e
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd $DIR

./download_deps

ant -buildfile android-profile-facebook.xml -Dsoomla.filename="AndroidProfileFacebook" all

cd - > /dev/null
