#!/bin/sh
set -e
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd $DIR

ANDROID_PROFILE_CACHE=$1

mkdir -p libs

if [ ! -f libs/simple-fb-4.0.9.jar ];
then
    if [ ! -f $ANDROID_PROFILE_CACHE/simple-fb-4.0.9.aar ];
    then
        curl -o $ANDROID_PROFILE_CACHE/simple-fb-4.0.9.aar.tmp https://dl.bintray.com/sromku/maven/com/sromku/simple-fb/4.0.9/simple-fb-4.0.9.aar
        mv $ANDROID_PROFILE_CACHE/simple-fb-4.0.9.aar.tmp $ANDROID_PROFILE_CACHE/simple-fb-4.0.9.aar
    fi
	mkdir -p simple-fb
	tar -xvf $ANDROID_PROFILE_CACHE/simple-fb-4.0.9.aar -C simple-fb
	mv simple-fb/classes.jar libs/simple-fb-4.0.9.jar
	rm -rf simple-fb
fi

if [ ! -f libs/gson-1.7.2.jar ];
then
    if [ ! -f $ANDROID_PROFILE_CACHE/gson-1.7.2.jar ];
    then
        curl -o $ANDROID_PROFILE_CACHE/gson-1.7.2.jar.tmp http://central.maven.org/maven2/com/google/code/gson/gson/1.7.2/gson-1.7.2.jar
        mv $ANDROID_PROFILE_CACHE/gson-1.7.2.jar.tmp $ANDROID_PROFILE_CACHE/gson-1.7.2.jar
    fi
    cp $ANDROID_PROFILE_CACHE/gson-1.7.2.jar libs/gson-1.7.2.jar
fi

if [ ! -h libs/AndroidProfile.jar ];
then
	ln -s ../../../build/AndroidProfile.jar libs/AndroidProfile.jar
fi

if [ ! -h libs/SoomlaAndroidCore.jar ];
then
	ln -s ../../../SoomlaAndroidProfile/libs/SoomlaAndroidCore.jar libs/SoomlaAndroidCore.jar
fi

if [ ! -h libs/square-otto-1.3.2.jar ];
then
	ln -s ../../../SoomlaAndroidProfile/libs/square-otto-1.3.2.jar libs/square-otto-1.3.2.jar
fi

if [ ! -d libs/facebook ];
then
    if [ ! -f $ANDROID_PROFILE_CACHE/facebook-4.6.0.zip ];
    then
        curl -L -o $ANDROID_PROFILE_CACHE/facebook-4.6.0.zip.tmp http://library.soom.la/fetch/android-profile-facebook/4.6.0?cf=dl_deps
        mv $ANDROID_PROFILE_CACHE/facebook-4.6.0.zip.tmp $ANDROID_PROFILE_CACHE/facebook-4.6.0.zip
    fi
	unzip $ANDROID_PROFILE_CACHE/facebook-4.6.0.zip -d libs/
fi
