#!/bin/sh
set -e
DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
cd $DIR

ANDROID_PROFILE_CACHE=~/.soomla/cache/android-profile
mkdir -p $ANDROID_PROFILE_CACHE

mkdir -p libs

SIMPLEFB_LIB_NAME=simple-fb-4.0.9.jar
SIMPLEFB_ARCH_NAME=simple-fb-4.0.9.aar
if [ ! -f libs/$SIMPLEFB_LIB_NAME ];
then
    if [ ! -f $ANDROID_PROFILE_CACHE/$SIMPLEFB_ARCH_NAME ];
    then
        echo "Downloading Android Simple Facebook..."
        curl -Lo $ANDROID_PROFILE_CACHE/$SIMPLEFB_ARCH_NAME.tmp https://dl.bintray.com/sromku/maven/com/sromku/simple-fb/4.0.9/simple-fb-4.0.9.aar
        mv $ANDROID_PROFILE_CACHE/$SIMPLEFB_ARCH_NAME.tmp $ANDROID_PROFILE_CACHE/$SIMPLEFB_ARCH_NAME
    fi
	mkdir -p simple-fb
	tar -xvf $ANDROID_PROFILE_CACHE/$SIMPLEFB_ARCH_NAME -C simple-fb
	mv simple-fb/classes.jar libs/$SIMPLEFB_LIB_NAME
	rm -rf simple-fb
fi

GSON_LIB_NAME=gson-1.7.2.jar
if [ ! -f libs/$GSON_LIB_NAME ];
then
    if [ ! -f $ANDROID_PROFILE_CACHE/$GSON_LIB_NAME ];
    then
        echo "Downloading GSON Library..."
        curl -Lo $ANDROID_PROFILE_CACHE/$GSON_LIB_NAME.tmp http://central.maven.org/maven2/com/google/code/gson/gson/1.7.2/gson-1.7.2.jar
        mv $ANDROID_PROFILE_CACHE/$GSON_LIB_NAME.tmp $ANDROID_PROFILE_CACHE/$GSON_LIB_NAME
    fi
    cp $ANDROID_PROFILE_CACHE/$GSON_LIB_NAME libs/$GSON_LIB_NAME
fi

if [ ! -h libs/AndroidProfile.jar ];
then
	ln -s ../../../build/AndroidProfile.jar libs/AndroidProfile.jar
fi

if [ ! -h libs/SoomlaAndroidCore.jar ];
then
	ln -s ../../../SoomlaAndroidProfile/libs/SoomlaAndroidCore.jar libs/SoomlaAndroidCore.jar
fi

if [ ! -h libs/square-otto-1.3.2.jar ];
then
	ln -s ../../../SoomlaAndroidProfile/libs/square-otto-1.3.2.jar libs/square-otto-1.3.2.jar
fi

FACEBOOK_LIB_NAME=facebook-4.6.0.zip
if [ ! -d libs/facebook ];
then
    if [ ! -f $ANDROID_PROFILE_CACHE/$FACEBOOK_LIB_NAME ];
    then
        echo "Downloading Facebook Android SDK..."
        curl -L -o $ANDROID_PROFILE_CACHE/$FACEBOOK_LIB_NAME.tmp http://library.soom.la/fetch/android-profile-facebook/4.6.0?cf=dl_deps
        mv $ANDROID_PROFILE_CACHE/$FACEBOOK_LIB_NAME.tmp $ANDROID_PROFILE_CACHE/$FACEBOOK_LIB_NAME
    fi
	unzip $ANDROID_PROFILE_CACHE/$FACEBOOK_LIB_NAME -d libs/
fi
